-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 20:39:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escola` ;

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8mb4 ;
USE `escola` ;

-- -----------------------------------------------------
-- Table `escola`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`alunos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ra` CHAR(10) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL DEFAULT 'Centro',
  `cidade` VARCHAR(50) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cep` CHAR(9) NOT NULL,
  `fone_res` CHAR(15) NULL DEFAULT NULL,
  `fone_cel` CHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `escola`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`cursos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `escola`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`matriculas` (
  `alunos_id` INT(11) NOT NULL,
  `cursos_id` INT(11) NOT NULL,
  `turma` CHAR(3) NULL DEFAULT NULL,
  `dt_matricula` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`alunos_id`, `cursos_id`),
  INDEX `fk_matriculas_cursos_idx` (`cursos_id` ASC),
  INDEX `fk_matriculas_alunos_idx` (`alunos_id` ASC),
  CONSTRAINT `fk_matriculas_alunos`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `escola`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_cursos`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `escola`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
